site_name: MIDB Open Data Repository SOP

theme:
  name: readthedocs
  custom_dir: docs/overrides # for template overrides, used in this case for addition of "Page Last Updated: <DATE>" to pages

markdown_extensions:
  - toc:
      permalink: '🔗' 
  - admonition

extra_javascript:
  - js/extra.js

plugins:
  - search
  - git-revision-date-localized:
      type: date

docs_dir: docs
nav:
  - About:
     - MIDB Open Data Initiative: index.md
  - Step-by-Step Guide:
      - "Step 1: Prepare Data": sop/prep-data.md 
      - "Step 2: Create AWS S3 Bucket": sop/aws.md
      - "Step 3: DataLad": sop/datalad.md
  - Resources: helper-files/resources.md
  - Checklist: helper-files/checklist.md
  - Appendix:
      - AWS Bucket Configuration: appendix/aws-bucket-config.md
      - Conda Environment Configuration: appendix/conda-env-config.md
      - Tracking Repo Usage: appendix/access-logging.md
      - OpenNeuro Integration: appendix/openneuro.md
      - Troubleshooting: appendix/troubleshooting.md
      - Maintenance: appendix/maintenance.md
      
      

      
