site_name: Open Data Repository SOP
theme: readthedocs

markdown_extensions:
  - toc:
      permalink: '🔗' 

extra_javascript:
  - js/extra.js

plugins:
  - search
docs_dir: docs
nav:
  - About: index.md
  - Create AWS S3 Bucket: aws.md
  - Tracking Repo Usage: access-logging.md
  - "Local Installation/Configuration": installation.md
  - Prepare Data: dataprep.md
  - "Initialize & Configure DataLad": datalad-init.md
  - OpenNeuro Integration: openneuro.md
  - Maintenance: maintenance.md
      
