site_name: MIDB Open Data Repository SOP

theme:
  name: readthedocs
  custom_dir: docs/overrides # for template overrides, used in this case for addition of "Page Last Updated: <DATE>" to pages

markdown_extensions:
  - toc:
      permalink: '🔗' 
  - admonition

plugins:
  - search
  - git-revision-date-localized:
      type: date

docs_dir: docs
nav:
  - MIDB Open Data Initiative: index.md
  - Step-by-Step Guide:
      - First Steps: sop/first-steps.md
      - Prep Source Data: sop/prep-data.md
      - AWS Submission: sop/prep-submission.md
      - Environment Setup: sop/setup.md
      - DataLad Setup: sop/datalad.md
  - Appendix:
      - Resources: appendix/resources.md
      - Tracking Repo Usage: appendix/access-logging.md
      - OpenNeuro Integration: appendix/openneuro.md
      - How to Update Repo: appendix/maintenance.md
      
      

      
