site_name: Open Data Initiative Docs
theme: readthedocs

markdown_extensions:
  - toc:
      permalink: '🔗' 

extra_javascript:
  - js/extra.js

plugins:
  - search
docs_dir: docs
nav:
  - About: index.md
  - "Step 1: Installation": installation.md
  - "Step 2: Prepare Data": dataprep.md
  - "Step 3: Initalize & Configure DataLad": datalad-init.md
  - "Step 4: OpenNeuro Integration": openneuro.md
  - Making Changes: making-changes.md
      
