site_name: Open Data Initiative Docs
theme: readthedocs

markdown_extensions:
  - toc:
      permalink: '🔗' 

extra_javascript:
  - js/extra.js

plugins:
  - search
docs_dir: docs
nav:
  - About: index.md
  - Setup: setup.md
  - Making Changes: making-changes.md
  - OpenNeuro: openneuro.md
      
