site_name: MIDB Open Data Repository SOP

theme:
  name: readthedocs
  custom_dir: docs/overrides # for template overrides, used in this case for addition of "Page Last Updated: <DATE>" to pages

markdown_extensions:
  - toc:
      permalink: '🔗' 
  - admonition

extra_javascript:
  - js/extra.js

plugins:
  - search
  - git-revision-date-localized:
      type: date

docs_dir: docs
nav:
  - About:
     - Internal SOP for New Repositories: index.md
  - Step-by-Step Guide:
      - "Step 1: Prepare Data": sop/step1-prep-data.md 
      - "Step 2: Create AWS S3 Bucket": sop/step2-aws.md
      - "Step 3: DataLad": sop/step3-datalad.md
  - Checklist: checklist.md
  - Appendix:
      - AWS Bucket Configuration: appendix/aws-bucket-config.md
      - Conda Environment Configuration: appendix/conda-env-config.md
      - Tracking Repo Usage: appendix/access-logging.md

  - OLD PAGES UNDER REVIEW:
      - DRAFT CONTENT: EXTRA.md
      - "Local Installation/Configuration": installation.md
      - OpenNeuro Integration: openneuro.md
      - Maintenance: maintenance.md

      
